#!/usr/bin/zsh

export PATH=$PATH:/opt/node-v22.2.0-linux-x64/bin

alias eza='eza -abghlm --git --icons -s=type --time-style=long-iso --color-scale'

export PATH=$PATH:/opt/fltter/bin
export CHROME_EXECUTABLE=/usr/bin/chromium

export RUSTUP_HOME=/opt/Rust/rustup
export CARGO_HOME=/opt/Rust/cargo

export PATH=$PATH:$CARGO_HOME/bin
source $CARGO_HOME/env
